FROM oven/bun:latest 

WORKDIR /usr/src/app 
RUN apt-get update -y && apt-get install -y openssl

# Copy root package.json and lockfile
COPY bun.lock ./
COPY packages ./packages
# Copy the api package.json
COPY package.json ./
COPY turbo.json ./
COPY apps/web/package.json ./apps/web/package.json


# Copy app source
COPY apps/web ./apps/web
RUN bun install --no-frozen-lockfile

RUN bun run build --filter=web

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]
