FROM oven/bun:latest 

WORKDIR /usr/src/app 

RUN apt-get update -y && apt-get install -y openssl
# Copy root package.json and lockfile
COPY package.json ./
COPY bun.lock ./
# Copy the api package.json
COPY apps/dashboard/package.json ./apps/dashboard/package.json

RUN bun install

# Copy app source
COPY . .

COPY packages ./packages
RUN cd packages/auth-db && bunx prisma generate
RUN cd packages/database && bunx prisma generate


EXPOSE 5003

CMD [ "bun", "run", "start:dashboard" ]