FROM oven/bun:latest 

WORKDIR /usr/src/app 

# Copy root package.json and lockfile
COPY package.json ./
COPY bun.lock ./
COPY packages ./packages
# Copy the api package.json
COPY apps/dashboard/package.json ./apps/dashboard/package.json

RUN bun install

# Copy app source
COPY . .

RUN cd packages/auth-db && bunx prisma generate
RUN cd packages/database && bunx prisma generate

RUN apt-get update -y && apt-get install -y openssl

EXPOSE 5003

CMD [ "bun", "run", "start:dashboard" ]