FROM oven/bun:latest 

WORKDIR /usr/src/app 

RUN apt-get update -y && apt-get install -y openssl
# Copy root package.json and lockfile
COPY package.json ./
COPY bun.lock ./
# Copy the api package.json
COPY apps/api-gateway/package.json ./apps/api-gateway/package.json

RUN bun install

# Copy app source
COPY . .

COPY packages ./packages

EXPOSE 5001

CMD [ "bun", "run", "start:gateway" ]