FROM oven/bun:latest 

WORKDIR /usr/src/app 

# Copy root package.json and lockfile
COPY package.json ./
COPY bun.lock ./
COPY packages ./packages
# Copy the api package.json
COPY apps/api-gateway/package.json ./apps/api-gateway/package.json

RUN bun install

# Copy app source
COPY . .

RUN apt-get update -y && apt-get install -y openssl

EXPOSE 5001

CMD [ "bun", "run", "start:gateway" ]